# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-04 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventoryitem',
            options={'verbose_name': 'Инвентарная позиция', 'verbose_name_plural': 'Инвентарные позиции'},
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='item_details',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='item_name',
            field=models.CharField(max_length=200, verbose_name='Наименование'),
        ),
        migrations.AlterModelTable(
            name='inventoryitem',
            table='inventory_items',
        ),
    ]
