# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-04 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20151204_2309'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiscItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование')),
                ('details', models.TextField(verbose_name='Описание')),
            ],
            options={
                'db_table': 'misc_items',
                'verbose_name': 'Инвентарная позиция',
                'verbose_name_plural': 'Прочие позиции',
            },
        ),
        migrations.CreateModel(
            name='TestSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование')),
                ('details', models.TextField(verbose_name='Описание')),
                ('manufacturer', models.CharField(max_length=200, verbose_name='Производитель')),
            ],
            options={
                'db_table': 'test_systems',
                'verbose_name': 'Испытательная система',
                'verbose_name_plural': 'Испытательные системы',
            },
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование')),
                ('details', models.TextField(verbose_name='Описание')),
                ('manufacturer', models.CharField(max_length=200, verbose_name='Производитель')),
            ],
            options={
                'db_table': 'tools',
                'verbose_name': 'Средство измерений',
                'verbose_name_plural': 'Средства измерений',
            },
        ),
        migrations.DeleteModel(
            name='InventoryItem',
        ),
    ]
