# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-04 21:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20151204_2347'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tool',
            options={'verbose_name': 'Средство измерений', 'verbose_name_plural': 'Приборы и средства измерений'},
        ),
    ]
