# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-04 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20151205_0013'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование')),
                ('code', models.CharField(max_length=50, verbose_name='Код')),
                ('inventory_number', models.CharField(max_length=50, verbose_name='Номенклатурный или инвентарный номер')),
                ('unit', models.CharField(max_length=50, verbose_name='Единица измерения')),
                ('price', models.CharField(max_length=50, verbose_name='Цена, руб.')),
                ('quantity', models.CharField(max_length=50, verbose_name='Фактическое наличие (количество)')),
                ('total_price', models.CharField(max_length=50, verbose_name='Фактическая стоимость (сумма, руб.)')),
                ('actual_placement', models.CharField(max_length=50, verbose_name='Фактическое расположение')),
            ],
            options={
                'verbose_name': 'Инвентарная позиция',
                'verbose_name_plural': 'Инвентарные позиции',
            },
        ),
        migrations.DeleteModel(
            name='MiscItem',
        ),
        migrations.DeleteModel(
            name='TestSystem',
        ),
        migrations.DeleteModel(
            name='Tool',
        ),
    ]
