# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-04 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20151205_0030'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование')),
                ('code', models.CharField(max_length=50, verbose_name='Код')),
                ('inventory_number', models.CharField(max_length=50, verbose_name='Номенклатурный или инвентарный номер')),
                ('unit', models.CharField(max_length=50, verbose_name='Единица измерения')),
                ('price', models.CharField(max_length=50, verbose_name='Цена, руб.')),
                ('quantity', models.CharField(max_length=50, verbose_name='Фактическое наличие (количество)')),
                ('total_price', models.CharField(max_length=50, verbose_name='Фактическая стоимость (сумма, руб.)')),
                ('actual_placement', models.CharField(max_length=50, verbose_name='Фактическое расположение')),
            ],
            options={
                'verbose_name': 'Испытательная система',
                'db_table': 'test_systems',
                'verbose_name_plural': 'Испытательные системы',
            },
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование')),
                ('code', models.CharField(max_length=50, verbose_name='Код')),
                ('inventory_number', models.CharField(max_length=50, verbose_name='Номенклатурный или инвентарный номер')),
                ('unit', models.CharField(max_length=50, verbose_name='Единица измерения')),
                ('price', models.CharField(max_length=50, verbose_name='Цена, руб.')),
                ('quantity', models.CharField(max_length=50, verbose_name='Фактическое наличие (количество)')),
                ('total_price', models.CharField(max_length=50, verbose_name='Фактическая стоимость (сумма, руб.)')),
                ('actual_placement', models.CharField(max_length=50, verbose_name='Фактическое расположение')),
            ],
            options={
                'verbose_name': 'Средство измерений',
                'db_table': 'tools',
                'verbose_name_plural': 'Приборы и средства измерений',
            },
        ),
        migrations.RenameModel(
            old_name='InventoryItem',
            new_name='MiscItem',
        ),
        migrations.AlterModelOptions(
            name='miscitem',
            options={'verbose_name': 'Инвентарная позиция', 'verbose_name_plural': 'Прочие позиции'},
        ),
        migrations.AlterModelTable(
            name='miscitem',
            table='misc_items',
        ),
    ]
