# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-04 21:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20151205_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='last_test_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата поверки'),
        ),
        migrations.AddField(
            model_name='tool',
            name='next_test_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Срок поверки'),
        ),
    ]
