# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-04 22:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_auto_20151205_0053'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsystem',
            name='last_test_date',
            field=models.DateField(null=True, verbose_name='Дата поверки'),
        ),
        migrations.AddField(
            model_name='testsystem',
            name='manufacturer',
            field=models.CharField(max_length=200, null=True, verbose_name='Производитель'),
        ),
        migrations.AddField(
            model_name='testsystem',
            name='next_test_date',
            field=models.DateField(null=True, verbose_name='Срок поверки'),
        ),
        migrations.AddField(
            model_name='testsystem',
            name='purpose',
            field=models.CharField(choices=[('К', 'Климатические испытания'), ('М', 'Механические испытания'), ('В', 'Вакуумные испытания')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='testsystem',
            name='specification',
            field=models.TextField(default='', max_length=1000, verbose_name='Технические характеристики'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testsystem',
            name='year_of_production',
            field=models.IntegerField(null=True, verbose_name='Год выпуска'),
        ),
        migrations.AddField(
            model_name='tool',
            name='manufacturer',
            field=models.CharField(max_length=200, null=True, verbose_name='Производитель'),
        ),
        migrations.AddField(
            model_name='tool',
            name='specification',
            field=models.TextField(default='', max_length=1000, verbose_name='Технические характеристики'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tool',
            name='year_of_production',
            field=models.IntegerField(null=True, verbose_name='Год выпуска'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='last_test_date',
            field=models.DateField(null=True, verbose_name='Дата поверки'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='next_test_date',
            field=models.DateField(null=True, verbose_name='Срок поверки'),
        ),
    ]
