# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-04 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_auto_20151205_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testsystem',
            name='manufacturer',
            field=models.CharField(default='', max_length=200, verbose_name='Производитель'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testsystem',
            name='purpose',
            field=models.CharField(choices=[('К', 'Климатические испытания'), ('М', 'Механические испытания'), ('В', 'Вакуумные испытания')], max_length=1, null=True, verbose_name='Назначение'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='manufacturer',
            field=models.CharField(default='', max_length=200, verbose_name='Производитель'),
            preserve_default=False,
        ),
    ]
