# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-10 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_auto_20151205_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miscitem',
            name='name',
            field=models.TextField(max_length=200, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='testsystem',
            name='name',
            field=models.TextField(max_length=200, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='name',
            field=models.TextField(max_length=200, verbose_name='Наименование'),
        ),
    ]
