# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-10 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_auto_20151210_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testsystem',
            name='purpose',
            field=models.CharField(choices=[('К', 'Климатические испытания'), ('М', 'Механические испытания'), ('В', 'Вакуумные испытания'), ('П', 'Испытания на воздействие пыли')], max_length=1, null=True, verbose_name='Назначение'),
        ),
    ]
